---
users:
  - real_name: Real Name
    github_name: github_username
    slack_id: slack_id
    gitlab_name: gitlab_username

repos:
  <organisation>:
    - <repo>

projects:
  <group>:
    - <project>

channel: <pull-requests-channel>
gitlab_domain: <gitlab-instance-domain>