---
users:
  - real_name: Real Name
    github_name: github_username
    slack_id: slack_id

repos:
  <organisation>:
    - <repo>

projects:
  <group>:
    - <project>

channel: <pull-requests-channel>