---
app:
  users:
    - real_name: Real Name
      slack_id: slack_id
      github_name: github_username
      gitlab_name: gitlab_username


github:
  enabled: true
  repositories:
    <owner>:
      - <repo>

gitlab:
  enabled: true
  domain: gitlab.example.com
  projects:
    <group>:
      - <project>
